### ISSUE TITLE
textDocument/implementation is broken

### ISSUE THREAD

**Issue by Riatre** [MaskRay/ccls#100]
There are 2 issues, both introduced in https://github.com/MaskRay/ccls/commit/53632bd92015c6b08d1f7a543a0b58ca25c2e4bb:
1. The new `Handler_textDocumentImplementation` calls `Handler_cclsInheritance` but never initialize its `.db`, `.project` etc.
2. Same to 1, `request.id` is not copied to new request so ccls replies with a wrong id.

**Comment by MaskRay** [comment]
Thanks. Fixed in e4ea373f6f44d80aa94f6536dfea95de69e81104

**Comment by Riatre** [comment]
Unfortunately this is still broken, turns out it returns base functions/types instead of implementations due to forget setting derived = true

**Comment by MaskRay** [comment]
Thanks. 6fc35ab8662b77111783139d9e0ebbc531d9447d
