### ISSUE TITLE
clang_translation_unit.cc:103  libclang crashed 

### ISSUE THREAD

**Issue by ZWindL** [MaskRay/ccls#14]
OS: Arch linux with testing on;
neovim version: 0.2.2-6
the ccls package is installed from aur (ccls-git).
Language client plug is already up to date.

I wrote a simplest C++ source file with a main function and `std::cout << "hello" << std::endl`, and it can't 
```
(   0.019s) [indexer2]clang_translation_unit.cc:103   
| libclang crashed for /home/zwindl/test/cpp/test/a.cc.
 Please try running the following, identify which flag causes the issue, and report a bug. 
ccls will then filter the flag for you  automatically:
 %clang /home/zwindl/test/cpp/test/a.cc -fsyntax-only
```
After I run that command, there's nothing appeared  :(

**Comment by MaskRay** [comment]
Thanks. https://github.com/maskray/ccls/blob/master/src/filesystem.cc#L8 was broken

SHould be fixed now

**Comment by ZWindL** [comment]
Ok, thanks, I'll close it.

**Comment by ZWindL** [comment]
This issue still exists, I deleted the original log file, and here's the complete new issue file.
https://ptpb.pw/ibM8

**Comment by MaskRay** [comment]
Can you build from source and see if that works? 

https://github.com/MaskRay/ccls/wiki/Getting-started
`cmake -H. -Brelease -DSYSTEM_CLANG=on -DUSE_SHARED_LLVM=on`

**Comment by ZWindL** [comment]
It's weird, using the system-clang it can't works, but with the build option from wiki(which uses the external clang archive), it works.

**Comment by ZWindL** [comment]
The same issue appeared with system clang. btw.  It works but `cout`, `cin` can't be completed with it, well as the header files and the members from header files, like `stack`, maybe it caused by my `compile_commands.json`, it only has a `[]`.

**Comment by MaskRay** [comment]
if compile_commands.json is empty there will be no initially indexed files.

**Comment by ZWindL** [comment]
Alright, thanks a lot.

**Comment by MaskRay** [comment]
`rm -r /tmp/ccls; CCLS_TRACEME=1 LIBCLANG_DISABLE_CRASH_RECOVERY=1 v a.cc +'normal ,a`

```vim
nn ,al :LanguageClientStart<cr>
```

https://www.archlinux.org/packages/extra/x86_64/clang/ clang 6.0.0-1 compiled from https://releases.llvm.org/ cfe-6.0.0-src.tar.xz somewhere in `libclangBasic.so` is buggy

**Comment by MaskRay** [comment]
environment vars

**Comment by ZWindL** [comment]
OK, seems I should waiting for Arch fix the problem.

**Comment by MaskRay** [comment]
Duplicate of https://github.com/MaskRay/ccls/issues/30
