### ISSUE TITLE
Poor diagnostics compared to clangd

### ISSUE THREAD

**Issue by RedBeard0531** [MaskRay/ccls#391]
### Observed behavior

This file shows no diagnostics with ccls but shows helpful diagnostics with clangd:
```cpp
#define MACRO(x) func(x);
void func();
void func(int);
void test() {
    MACRO("");
}
```

### Expected behavior

ccls should have the same diagnostics output as clangd

### Steps to reproduce

1. Paste that code into a file
2. compare diagnostics produces with ccls vs clangd

### System information

* ccls version (`git describe --tags --long`): `0.20190314-7-gb731e6ca`
* clang version: `clangd version 8.0.0 (tags/RELEASE_800/final)`
* OS: Linux
* Editor: nvim
* Language client (and version): coc.nvim master

**Comment by MaskRay** [comment]
Nice catch! The problem was that Note::concerned was not propagated to Diag::concerned. Fixed in HEAD. I may adjust the code a bit recently

**Comment by RedBeard0531** [comment]
This is still an issue, although it is better. Using the same code, I now get this with ccls:
![image](https://user-images.githubusercontent.com/118456/57717754-ebaa2f80-7649-11e9-95b6-2e9e6ae01997.png)

And this with clangd:
![image](https://user-images.githubusercontent.com/118456/57717849-18f6dd80-764a-11e9-9fd8-9a1709dc0cac.png)

**Comment by MaskRay** [comment]
I think the problem is that coc.nvim doesn't support `publishDiagnostics.relatedInformation`.

In vscode-ccls, I see:

```
[ccls] no matching function for call to 'func' [2]
a.cc(3, 6): candidate function not viable: no known conversion from 'const char [1]' to 'int' for 1st argument
a.cc(2, 6): candidate function not viable: requires 0 arguments, but 1 was provided
```

`a.cc(3, 6)` is a clickable button.
